# Generated by Django 2.1.4 on 2019-02-11 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ammamanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=255)),
                ('accepted1', models.BooleanField(default=False)),
                ('accepted2', models.BooleanField(default=False)),
                ('final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('nname', models.CharField(max_length=40)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('nc', models.IntegerField(default=0)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FightOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('bout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bout', to='ammamanager.Bout')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_event', to='ammamanager.Event')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_fighter', to='ammamanager.Fighter')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='ammamanager.Fighter')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('round', models.IntegerField(default=0)),
                ('min', models.IntegerField(default=0)),
                ('sec', models.IntegerField(default=0)),
                ('bout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishedbout', to='ammamanager.Bout')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishedevent', to='ammamanager.Event')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='ammamanager.Fighter')),
            ],
        ),
        migrations.AddField(
            model_name='bout',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='ammamanager.Event'),
        ),
        migrations.AddField(
            model_name='bout',
            name='fighter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f1', to='ammamanager.Fighter'),
        ),
        migrations.AddField(
            model_name='bout',
            name='fighter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f2', to='ammamanager.Fighter'),
        ),
    ]
