# Generated by Django 2.1.4 on 2019-02-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ammamanager', '0003_fighter_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='weight',
            field=models.CharField(choices=[('FLW', 'Flyweight'), ('BW', 'Bantamweight'), ('FW', 'Featherweight'), ('LW', 'Lightweight'), ('WW', 'Welterweight'), ('MW', 'Middleweight'), ('LHW', 'Light Heavyweight'), ('HW', 'Heavyweight'), ('WSW', 'Womens Strawweight'), ('WBW', 'Womens Bantamweight'), ('WFW', 'Womens Featherweight')], default='FLW', max_length=4),
        ),
    ]
