# Generated by Django 2.1.4 on 2018-12-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ammamanager', '0004_auto_20181113_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='interests',
            new_name='Certifications',
        ),
    ]
