# Generated by Django 2.1.4 on 2019-02-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ammamanager', '0005_auto_20190218_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
