# Generated by Django 2.1.4 on 2019-02-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ammamanager', '0006_fighter_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
