# Generated by Django 2.1.3 on 2019-04-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ammamanager', '0008_auto_20190412_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
