# Generated by Django 2.1.3 on 2019-04-14 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ammamanager', '0009_fighter_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 15, 0, 21, 28, 738978)),
        ),
    ]
