# Generated by Django 2.1.3 on 2019-04-18 01:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ammamanager', '0011_auto_20190417_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedfight',
            name='loser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='ammamanager.Fighter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 18, 2, 23, 4, 207496)),
        ),
    ]
