# Generated by Django 2.1.3 on 2019-04-22 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ammamanager', '0013_auto_20190418_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 4, 53, 44, 332560)),
        ),
        migrations.AddField(
            model_name='fighter',
            name='initialPointsBoost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finishedfight',
            name='loserPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finishedfight',
            name='winnerPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 4, 53, 44, 331572)),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='points',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='finishedfight',
            name='method',
            field=models.CharField(choices=[('KO', 'Knock out'), ('SUB', 'Submission'), ('DEC', 'Decision'), ('DRAW', 'Draw'), ('NC', 'No Contest')], default='DEC', max_length=5),
        ),
    ]
