# Generated by Django 2.1.3 on 2019-04-28 03:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ammamanager', '0014_auto_20190422_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 4, 35, 13, 922613)),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 4, 35, 13, 924113)),
        ),
        migrations.AlterField(
            model_name='finishedfight',
            name='min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='finishedfight',
            name='round',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='finishedfight',
            name='sec',
            field=models.IntegerField(default=1),
        ),
    ]
